### ISSUE TITLE
new discussion does not appear

### ISSUE THREAD

**Issue by VladimirAlexiev** [zazuko/ontology-manager#10]
- went to http://editor.zazuko.com/schema/RailroadWaggon
- clicked New Thread
- entered http://editor.zazuko.com/discussion/120
- but that discussion does not appear on the http://editor.zazuko.com/schema/RailroadWaggon page

**Comment by vhf** [comment]
Thanks, I will investigate.

**Comment by vhf** [comment]
Solved by 232ab85081deec6afe7d7a8351542fb1992ee39c . It will be deployed on http://editor.zazuko.com shortly.

**Comment by vhf** [comment]
http://editor.zazuko.com/schema/RailroadWaggon
