### ISSUE TITLE
Lost draft property definitions in schema.ld.admin.ch

### ISSUE THREAD

**Issue by JLCochardSFA** [zazuko/ontology-manager#29]
I created the class ZefixOrganisation and I started adding properties to this definition (identifier, address, municipality, and legalName). I saved my draft but everything seems to be lost.

**Comment by l00mi** [comment]
That sounds bad. Its difficult to investigate with not more details. I propose a short screen share?

**Comment by JLCochardSFA** [comment]
Hi,

I’m available for such a screen-sharing session until 6PM today.

Regards,
Jean-Luc

De : Michael Luggen ***@***.***>
Envoyé : mercredi, 26 mai 2021 07:16
À : zazuko/ontology-manager ***@***.***>
Cc : Cochard Jean-Luc BAR ***@***.***>; Author ***@***.***>
Objet : Re: [zazuko/ontology-manager] Lost draft property definitions in schema.ld.admin.ch (#29)


That sounds bad. Its difficult to investigate with not more details. I propose a short screen share?
