### ISSUE TITLE
Where to configure the hostname

### ISSUE THREAD

**Issue by MPParsley** [zazuko/ontology-manager#45]
'npm run dev' always runs on localhost, where or how can the hostname/port be configured?

**Comment by ktk** [comment]
It is using nuxt for that, please check the [offical doc](https://nuxtjs.org/docs/features/configuration/#edit-host-and-port).

But are you sure it only binds to localhost? According to https://github.com/zazuko/ontology-manager/blob/master/package.json#L10 I would say it binds to all interfaces.

**Comment by MPParsley** [comment]
Thank you for the feedback. Indeed it binds to all hosts.

When using an 'external' hostname the application runs into a lot of JS errors as it tries to do GET to localhost:3000.

I got most of it to work by adding this to the .env file:
```
EDITOR_HOST=myhost:3000
EDITOR_PROTOCOL=http
```

See #46.
